services:
  - type: web
    name: django-job-portal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn django_job_portal.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: django_job_portal.settings
      - key: PYTHON_VERSION
        value: 3.12
